

build:
  compile:
    image: node:6.3.1
    pull: true
    commands:
      - npm update
      - npm run build


publish:
  docker:
    repo: stackdot/cuid
    tag:
      - '$${BRANCH/master/latest}'
      - '$$BRANCH.$$BUILD_NUMBER'
    registry: $$DOCKER_REGISTRY
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    storage_driver: overlay
  

cache:
  mount:
    - node_modules

